version: "3"

services:
    
  web:
    build: ./web
    command: yarn start
    ports:
      - "80:3000"
    volumes:
      - ./web:/usr/app
    depends_on:
      - api
    
  api:
    build: ./backend
    command: adonis migration:run
    command: adonis serve --dev --polling
    environment: 
       DB_HOST: database
    ports:
      - "3333:3131"
    volumes:
      - ./backend:/usr/api

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
      MYSQL_USER: payhold
      MYSQL_PASSWORD: payhold
    ports: 
      - "3306:3306"

