version: "3"

services:
  web:
    build: ./web
    command: yarn start
    ports:
      - "80:3000"
    volumes:
      - ./web:/usr/app
    depends_on:
    - api
    
  api:
    build: ./backend
    command: adonis serve --dev --polling
    ports:
      - "3333:3131"
    volumes:
      - ./backend:/usr/api
