version: "3"

services:

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
      MYSQL_USER: payhold
      MYSQL_PASSWORD: payhold
    ports: 
      - "3306:3306"
